name: PingChecker
version: 1.0.1
main: com.elllzman.PingChecker.PingCheckerPlugin
commands:
  ping:
    usage: /ping [playername]
    permission: ping.main
permissions:
  ping.main:
    description: Allows use of the /ping command
    default: true